owner: jaimezpe
repo: bio-status
sites: 
  - name: Jaime
    url: https://www.jaimezpe.com
  - name: Founda
    url: https://www.founda.jaimezpe.com
assignees: 
  - AnandChowdhary
status-website:
  baseUrl: /bio-status
  name: Status
